name: poetry-update
description: "CI bot which updates poetry dependencies via PR."

runs:
  using: composite
  steps:
    - run: poetry install
      shell: bash

    - run: |
        POETRY_OUTDATED=$(poetry show --outdated)
        echo "POETRY_OUTDATED<<EOF" >> $GITHUB_ENV
        echo "$POETRY_OUTDATED" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV
      shell: bash

    - run: poetry update
      shell: bash
