name: poetry-update
description: "CI bot which updates poetry dependencies via PR."

inputs:
  install_command:
    description: Install command
    default: poetry install
    required: false

  show_outdated_command:
    description: Show outdated command
    default: poetry show --outdated
    required: false

  update_command:
    description: Update command
    default: poetry update
    required: false

runs:
  using: composite
  steps:
    - run: ${{ inputs.install_command }}
      shell: bash

    - run: |
        POETRY_OUTDATED_BEFORE=$(${{ inputs.show_outdated_command }})
        echo "POETRY_OUTDATED_BEFORE<<EOF" >> $GITHUB_ENV
        echo "$POETRY_OUTDATED_BEFORE" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV
      shell: bash

    - run: |
        POETRY_UPDATED=$(${{ inputs.update_command }})
        echo "POETRY_UPDATED<<EOF" >> $GITHUB_ENV
        echo "$POETRY_UPDATED" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV
      shell: bash

    - run: |
        POETRY_OUTDATED_AFTER=$(${{ inputs.show_outdated_command }})
        echo "POETRY_OUTDATED_AFTER<<EOF" >> $GITHUB_ENV
        echo "$POETRY_OUTDATED_AFTER" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV
      shell: bash
