name: download-translations
description: "Download any lokalise changes and prepare a pull request"

inputs:
  token:
    description: Token used to create PR
    required: false

runs:
  using: composite
  steps:
    - run: poetry install
      shell: bash

    - run: |
        POETRY_OUTDATED=$(poetry show --outdated)
        echo "POETRY_OUTDATED<<EOF" >> $GITHUB_ENV
        echo "$POETRY_OUTDATED" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV
      shell: bash

    - run: poetry update
      shell: bash

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        delete-branch: true
        branch: poetry-update
        base: "main" # temp
        commit-message: "Update poetry dependencies"
        title: "Update poetry dependencies"
        body: |
          # Update poetry dependencies

          ```bash
          $ poetry show --outdated

          ${{ env.POETRY_OUTDATED }}
          ```

          _Note: there may be dependencies in the table above which were not updated as part of this PR.
          The reason is they require manual updating._
